name: Build and Release Plugin

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Adjust to your PHP version if needed

    - name: Prepare Plugin Zip
      run: |
        mkdir -p build
        cp -r module-watcher build/
        cd build
        zip -r module-watcher.zip module-watcher
        cd ..
        echo "module-watcher.zip prepared successfully."

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: build/module-watcher.zip
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}  # Use your PAT secret here
