name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP file
        run: |
          VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          mkdir -p release
          # Copy all files from the current directory to the release directory, excluding the release directory itself
          find . -maxdepth 1 ! -name 'release' -exec cp -r {} release/ \;
          cd release
          zip -r "../module-watcher-greg.zip" .
          cd ..
        working-directory: ./

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./module-watcher-greg.zip
          asset_name: module-watcher-greg.zip
          asset_content_type: application/zip