name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zipping plugin
        run: |
          mkdir -p release
          zip -r release/module-watch-greg.zip module-watch

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./module-watcher-greg.zip
          asset_name: module-watcher-greg.zip
          asset_content_type: application/zip